1178 px 98px/ 98px 48px
belokonivan1707/avenue pull request #2
Opened 2020-08-21 19:09 UTC by belokonivan1707

fixed

2020-08-29 11:39 UTC, fallinthehole requested changes
Looks good. Speed up on it and push the final fixes. @belokonivan1707

2020-08-29 11:39 UTC, fallinthehole commented on css/components/header.css
> +    width: 98px;
@belokonivan1707 how 'bout `box-sizing: border-box`? Try it next time

2020-08-29 11:39 UTC, fallinthehole commented on css/components/header.css
>      align-items: center;
You dont need for `align-items` since `display: flex` has been deleted. @belokonivan1707

2020-08-29 11:39 UTC, fallinthehole commented on css/components/header.css
> +    text-align: end;
`center`

2020-08-29 11:39 UTC, fallinthehole commented on css/components/header.css
> +.header-container {
You still don't get it. `.container` supposed to be a reusable class. Attach this class to the items you wanna fit into `1180px` width and set centre positioning. 

**Example of CSS code:** 
```
.container {
  width: 1180px;
  margin: 0 auto;
}
.header {
  background: red;
}
```

**Example of HTML code:**
```
<header class="header container">
    ... some shit here
</header>
<div class="some-other-content container">
    ... some content here
</div>
```

2020-08-29 12:18 UTC, belokonivan1707 commented on css/components/header.css
>      align-items: center;
+

2020-08-29 12:34 UTC, belokonivan1707 commented on css/components/header.css
> +.header-container {
+

2020-08-29 12:36 UTC, belokonivan1707 commented on css/components/header.css
> +.header-container {
Ладно, буду на русском, плохо ориентируюсь в гит хабе. 
Я убрал background-color из container-header и перенес его в header.

2020-08-29 12:39 UTC, belokonivan1707 commented on css/components/header.css
> +    text-align: end;
Этот момент мне не ясен, если я меняю justyfy-content: flex-end; на  justyfy-content: center; то все меню съезжает в центр, а мне ведь надо что бы оно было справа, не понимаю этот момент.

2020-08-29 12:51 UTC, belokonivan1707 commented on css/components/header.css
>      align-items: center;
Удалил align-items: center;

2020-08-29 12:59 UTC, belokonivan1707 commented on css/components/header.css
> +    width: 98px;
Ура! Понял, это новое свойство, использовал его!

2020-08-29 13:08 UTC, belokonivan1707 commented on css/components/header.css
> +    text-align: end;
Этот момент мне не ясен, если  меняю justify-content: flex-end; на justify-content:center; то все меню в header становиться в центр, как бы очевидно это не звучало , а мне ведь надо что бы оно было с права? я не понимаю...

2020-08-29 13:25 UTC, belokonivan1707 commented on css/components/header.css
> +    text-align: end;
Все, понял лучше, дважды тут комментарий удалял. 
Поменял text-align: end; на text-align: center;
Padding-right; 20px на padding-left: 40px;.
Я не уверен что правильно понял, когда был text-align: end; то текст был прижат справа к границе и было легко отступить 20px как в макете.

2020-08-31 10:40 UTC, fallinthehole requested changes

2020-08-31 10:40 UTC, fallinthehole commented on css/components/header.css
> +.header-container {
@belokonivan1707  Используй .container как отдельный класс. Читай коммент выше внимательно.

2020-08-31 18:19 UTC, Gleb-Petrov approved these changes
❤️ Your first approved Pull Request 🔥

2020-09-15 16:20 UTC, merged